/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.proj;

import edu.isu.cs2263.proj.JavaFX.FX;
import edu.isu.cs2263.proj.data.Facade;

import java.util.Objects;
import java.util.Scanner;

public class App {

    public static void basic(){
        //Global variables
        final int Player1 = 1;
        final int Player2 = 2;
        final int Player3 = 3;
        final int Player4 = 4;

        //Setup game
        Facade worker = new Facade();

        //get players
        boolean playersSelected = false;
        Scanner input = new Scanner(System.in);
        int numPlayers = 0;
        while (!playersSelected){
            System.out.println("How many players are there? (2-4)");
            String number = input.nextLine();
            playersSelected = true;
            if (Objects.equals(number, "2")){
                numPlayers = 2;
            }else if (Objects.equals(number, "3")){
                numPlayers = 3;
            }else if (Objects.equals(number, "4")){
                numPlayers = 4;
            }else {
                playersSelected = false;
            }
            worker.setupGame(numPlayers, false);
        }

        int currentPlayer = worker.chooseFirstPlayer();

        worker.showBoard();
    }

    public static void main(String[] args) {
        boolean launchUi = true;
        if (launchUi){
            FX.classApp(args);
        } else {
            basic();
        }
    }
}
