/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.proj;

import edu.isu.cs2263.proj.JavaFX.FX;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        boolean launchUi = false;
        if (launchUi){
            FX.classApp(args);
        }
    }
}
